import os

MIN_REQUIRED_COUNT = int(os.getenv("MIN_REQUIRED_COUNT", 100))
INIT_ANALYSIS_DURATION = float(os.getenv("INIT_ANALYSIS_DURATION", 0.5))
CONTINUOUS_ANALYSIS_DURATION = float(os.getenv("CONTINUOUS_ANALYSIS_DURATION", 3))

INFLUXDB_URL = os.getenv("INFLUXDB_URL", "http://localhost:10236")
INFLUXDB_TOKEN = os.getenv("INFLUXDB_TOKEN", "VHA3GuGcLOI7VPUiup4NGoWQ5Gh5ijtVSAaxeGnJnl1VjAO2KdIFvXFs0ti22By8oJBUDH31l7Gqcs4rvKJFIw==")
INFLUXDB_ORG = os.getenv("INFLUXDB_ORG", "my-org")
INFLUXDB_BUCKET = os.getenv("INFLUXDB_BUCKET", "dongho")

SENSOR_SERVICE_URL = os.getenv("SENSOR_SERVICE_URL", "http://localhost:10238")
GATEWAY_SERVICE_URL = os.getenv("GATEWAY_SERVICE_URL", "http://localhost:10241")